version: "3.9"

services:
    postgresql:
        image: postgres:13.3
        ports:
            - 5432:5432
        restart: on-failure
        volumes:
            - ./data/postgres/:/var/lib/postgresql:rw
        environment: 
            POSTGRES_USER: desarrollo
            POSTGRES_PASSWORD: desarroll0
            POSTGRES_DB: boilerplate
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U desarrollo -d pgdevdb"]
            interval: 10s
            timeout: 5s
            retries: 5
    django:
        build: 
            context: .
            dockerfile: ./.docker/app/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000 --settings=core.settings.local
        restart: on-failure
        volumes:
            - ./app/:/usr/src/app/:rw
            - ./data/static/:/static/:rw
            - ./media/:/media/:rw
            - ./data/logs:/logs:rw
        ports:
            - 8000:8000
        env_file:
            - ./.docker/app/.env
        depends_on:
            postgresql:
                condition: service_healthy